SELECT VEN_AUTORIZACAO, PRO_ID, VEN_CAIXA, VEN_QUANTIDADE FROM VENDAS V LEFT JOIN DADOSFP D ON V.VEN_AUTORIZACAO = D.FP_AUTORIZACAO WHERE FP_AUTORIZACAO IS NOT NULL

SELECT * FROM VENDAS V LEFT JOIN DADOSFP D ON V.VEN_AUTORIZACAO = D.FP_AUTORIZACAO WHERE FP_AUTORIZACAO IS NOT NULL

SELECT CONCAT("INSERT INTO MOVIMENTO (FP_AUTORIZACAO, PRO_ID, MOV_ECF , MOV_QUANTIDADE) VALUES ("), CONCAT("'",D.FP_AUTORIZACAO,"'") AS FP_AUTORIZACAO, V.PRO_ID AS PRO_ID, VEN_CAIXA AS MOV_ECF , VEN_QUANTIDADE AS MOV_QUANTIDADE, CONCAT(");") FROM DADOSFP D LEFT JOIN MOVIMENTO M ON M.FP_AUTORIZACAO = D.FP_AUTORIZACAO LEFT JOIN VENDAS V ON VEN_AUTORIZACAO = D.FP_AUTORIZACAO WHERE MOV_ID IS NULL AND VEN_ID IS NOT NULL AND FP_DATA_VENDA BETWEEN '2017-11-01' AND '2017-12-01'

SELECT D.FP_AUTORIZACAO AS FP_AUTORIZACAO, V.PRO_ID AS PRO_ID, VEN_CAIXA AS MOV_ECF , VEN_QUANTIDADE AS MOV_QUANTIDADE FROM DADOSFP D LEFT JOIN MOVIMENTO M ON M.FP_AUTORIZACAO = D.FP_AUTORIZACAO LEFT JOIN VENDAS V ON VEN_AUTORIZACAO = D.FP_AUTORIZACAO WHERE MOV_ID IS NULL AND VEN_ID IS NOT NULL AND FP_DATA_VENDA BETWEEN '2017-11-01' AND '2017-12-01'

SELECT VEN_AUTORIZACAO AS FP_AUTORIZACAO, VEN_CPF AS CLI_CPF, VEN_DATA_VENDA AS FP_DATA_VENDA, DATE_ADD(VEN_DATA_VENDA, interval PRO_DIAS day) AS FP_DATA_PROX_VENDA , VEN_CUPOM AS FP_CUPOM FROM VENDAS V LEFT JOIN DADOSFP D ON VEN_AUTORIZACAO = FP_AUTORIZACAO LEFT JOIN CLIENTES C ON VEN_CPF = C.CLI_CPF LEFT JOIN PRODUTO P ON P.PRO_ID = V.PRO_ID where FP_AUTORIZACAO IS NULL AND C.CLI_CPF IS NOT NULL GROUP BY VEN_AUTORIZACAO AND VEN_DATA_VENDA = '2017-11-30'


--COMANDO ABAIXO PARA LANÇAMENTO DA TABELA MOVIMENTO DE FORMA AUTOMATICO---
SELECT V.VEN_AUTORIZACAO AS FP_AUTORIZACAO, V.PRO_ID, V.VEN_CAIXA AS MOV_ECF , V.VEN_QUANTIDADE AS MOV_QUANTIDADE 
FROM VENDAS V LEFT JOIN PRODUTO P ON V.PRO_ID = P.PRO_ID
LEFT JOIN DADOSFP D ON V.VEN_AUTORIZACAO = D.FP_AUTORIZACAO 
LEFT JOIN CLIENTES C ON V.VEN_CPF = C.CLI_CPF 
LEFT JOIN MOVIMENTO M ON M.FP_AUTORIZACAO = D.FP_AUTORIZACAO
WHERE VEN_DATA_VENDA BETWEEN '2018-02-01' AND '2018-02-19' and D.FP_AUTORIZACAO is not null AND M.FP_AUTORIZACAO IS NULL order by VEN_DATA_VENDA



/*Abordaremos neste artigo as seguintes funções nativas do MySQL
date_add
Recomendada para adicionar valores a uma data.
date_sub
Recomendada para reduzir valores a uma data.
Sintaxe

DATE_ADD(date,INTERVAL expr unit)
DATE_SUB(date,INTERVAL expr unit)*/

/*
A lista de possibilidades aceitas pelo argumento unit é extensa, veja:
unit Valor	Esperado expr Format
MICROSECOND	Microssegundo
SECOND	Segundo
MINUTE	Minuto
HOUR	Hora
DAY	Dia
WEEK	Semana
MONTH	Mês
QUARTER	Trimestre
YEAR	Ano
SECOND_MICROSECOND	Segundo e Microssegundo
MINUTE_MICROSECOND	Minuto e Microssegundo
MINUTE_SECOND	Minuto e Segundo
HOUR_MICROSECOND	Hora e Microssegundo
HOUR_SECOND	Hora e Segundo
HOUR_MINUTE	Hora e Minuto
DAY_MICROSECOND	Dia e Microssegundo
DAY_SECOND	Dia e Segundo
DAY_MINUTE	Dia e Minuto
DAY_HOUR	Dia e Hora
YEAR_MONTH	Ano e Mês

*/

select date_add(now(), interval 30 day) 

/*concatenando coluna com alguma coisa*/

SELECT CONCAT(MOV_ID,"A") FROM MOVIMENTO 

